//! Cross-language conformance: the Rust implementation must reproduce, byte for
//! byte, the shared fixture in `conformance/vectors.json`.
//!
//! The fixture is generated by `conformance/generate.mjs` using **Node's
//! OpenSSL-backed Ed25519** — an implementation that shares no code with this
//! crate. So this test is a genuine cross-implementation check, not the
//! self-consistency check upstream v2.5.6 relied on:
//!
//! * upstream's Python suite never referenced the shared vector at all (it only
//!   re-verified its own output), and its 11 crypto tests were skipped in CI for
//!   want of the `cryptography` wheel;
//! * upstream removed `signature` only at the **root**, admitted floats into
//!   signed payloads, and signed the literal payload `null` if serialization
//!   failed.
//!
//! The first fixture entry is upstream's own vector
//! (`gsn-core/tests/cross_lang_signature.rs:11-14`), so passing this file also
//! proves that identities and signatures minted by agent-universe v2.5.6 remain
//! verifiable here.

use nau_core::identity::canonical::{canonical_object, CanonicalError};
use nau_core::identity::{Did, Keypair, PublicKey, DID_PREFIX, DID_PREFIX_LEGACY};
use serde_json::Value;

/// Upstream v2.5.6's own expected signature for the shared vector.
const UPSTREAM_SIGNATURE: &str =
    "e14d3f9e8204ea185ea4ba32a8117f262095ab9dac1352e1a7964ce36d3355c288dd6804ffa7daeb5f6eba9f30428f52702a75fd3efbb6a62555a7f24665da0e";
const UPSTREAM_PUBKEY: &str = "8a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c";
const UPSTREAM_DID_LEGACY: &str = "did:aip:34750f98bd59fcfc";

fn vectors() -> Value {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("conformance")
        .join("vectors.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("vectors.json must be valid JSON")
}

/// Map the fixture's error name onto the typed error we expect.
fn expected_error(kind: &str) -> fn(&CanonicalError) -> bool {
    match kind {
        "non_integer_number" => |e| matches!(e, CanonicalError::NonIntegerNumber(_)),
        "root_not_object" => |e| matches!(e, CanonicalError::RootNotObject(_)),
        "too_deep" => |e| matches!(e, CanonicalError::TooDeep),
        "number_out_of_range" => |e| matches!(e, CanonicalError::NumberOutOfRange(_)),
        other => panic!("vectors.json names an error this test does not know: {other}"),
    }
}

#[test]
fn identity_derivation_matches_the_fixture_and_upstream() {
    let doc = vectors();
    let seed_hex = doc["seed_hex"].as_str().expect("seed_hex");
    let keypair = Keypair::from_seed_hex(seed_hex).expect("seed parses");

    let expected_pub = doc["identity"]["public_key_hex"].as_str().unwrap();
    assert_eq!(keypair.public_key().to_hex(), expected_pub);
    // And that is upstream's pinned public key.
    assert_eq!(expected_pub, UPSTREAM_PUBKEY);

    let expected_nau = doc["identity"]["did_nau"].as_str().unwrap();
    assert_eq!(keypair.did().as_str(), expected_nau);
    assert!(expected_nau.starts_with(DID_PREFIX));

    let expected_legacy = doc["identity"]["did_legacy"].as_str().unwrap();
    assert_eq!(keypair.public_key().legacy_did().as_str(), expected_legacy);
    assert!(expected_legacy.starts_with(DID_PREFIX_LEGACY));
    // Upstream's pinned DID, unchanged.
    assert_eq!(expected_legacy, UPSTREAM_DID_LEGACY);

    // A legacy DID from upstream binds to the same key, so migration is safe.
    let legacy = Did::parse(UPSTREAM_DID_LEGACY).expect("legacy DID parses");
    assert!(legacy.matches_public_key(&keypair.public_key()));
}

#[test]
fn every_payload_reproduces_the_canonical_bytes_exactly() {
    let doc = vectors();
    let payloads = doc["payloads"].as_array().expect("payloads array");
    assert!(!payloads.is_empty(), "fixture must contain payloads");

    for entry in payloads {
        let id = entry["id"].as_str().unwrap();
        let input_text = entry["input_json"].as_str().unwrap();
        let expected = entry["canonical"].as_str().unwrap();

        let parsed: Value = serde_json::from_str(input_text)
            .unwrap_or_else(|e| panic!("[{id}] input_json must parse: {e}"));

        let derived = canonical_object(&parsed)
            .unwrap_or_else(|e| panic!("[{id}] canonicalization must succeed: {e}"));

        assert_eq!(
            derived, expected,
            "[{id}] canonical form differs\n  derived:  {derived}\n  expected: {expected}"
        );

        // canonical_payload must agree with canonical_object byte for byte.
        let via_payload = nau_core::identity::canonical_payload(&parsed)
            .unwrap_or_else(|e| panic!("[{id}] canonical_payload failed: {e}"));
        assert_eq!(
            String::from_utf8(via_payload.clone()).unwrap(),
            expected,
            "[{id}] canonical_payload disagrees with canonical_object"
        );

        // The fixture's own hex must match too, so no encoding ambiguity.
        if let Some(hex_expected) = entry["canonical_hex"].as_str() {
            assert_eq!(
                hex::encode(expected.as_bytes()),
                hex_expected,
                "[{id}] canonical_hex"
            );
            assert_eq!(
                hex::encode(&via_payload),
                hex_expected,
                "[{id}] payload hex"
            );
        }
    }
}

#[test]
fn signatures_produced_by_the_javascript_implementation_verify_here() {
    let doc = vectors();
    let keypair = Keypair::from_seed_hex(doc["seed_hex"].as_str().unwrap()).unwrap();
    let pk = keypair.public_key();

    for entry in doc["payloads"].as_array().unwrap() {
        let id = entry["id"].as_str().unwrap();
        let signature = entry["signature_hex"].as_str().unwrap();
        let canonical = entry["canonical"].as_str().unwrap();

        // Verify over the raw canonical bytes, independently of our own
        // canonicalization, so a signing/verifying bug is isolated from a
        // canonicalization bug.
        let sig = nau_core::Signature64::from_hex(signature)
            .unwrap_or_else(|e| panic!("[{id}] signature must decode: {e}"));
        let payload = canonical.as_bytes();
        pk.verify(payload, sig.as_bytes())
            .unwrap_or_else(|e| panic!("[{id}] JS-produced signature must verify: {e}"));

        // And the high-level API must verify the object that still carries its
        // signature field, because canonicalization strips it.
        let mut with_sig: Value =
            serde_json::from_str(entry["input_json"].as_str().unwrap()).unwrap();
        if let Some(obj) = with_sig.as_object_mut() {
            obj.insert("signature".into(), Value::String(signature.to_string()));
        }
        nau_core::identity::verify_payload(&with_sig, signature, &pk)
            .unwrap_or_else(|e| panic!("[{id}] verify_payload must accept the signed object: {e}"));
    }
}

#[test]
fn the_upstream_vector_is_byte_identical_including_the_signature() {
    let doc = vectors();
    let keypair = Keypair::from_seed_hex(doc["seed_hex"].as_str().unwrap()).unwrap();

    let entry = doc["payloads"]
        .as_array()
        .unwrap()
        .iter()
        .find(|p| p["id"] == "upstream-v2.5.6-compat")
        .expect("the upstream compatibility vector must be present");

    assert_eq!(
        entry["canonical"].as_str().unwrap(),
        r#"{"capabilities":["text-generation","mcp"],"did":"did:aip:34750f98bd59fcfc","name":"CrossLang","stake":100}"#,
        "upstream's exact canonical payload"
    );
    assert_eq!(
        entry["signature_hex"].as_str().unwrap(),
        UPSTREAM_SIGNATURE,
        "must equal upstream's pinned signature"
    );

    // And our deterministic Ed25519 must reproduce that same signature from the
    // same canonical bytes: signing the payload ourselves gives upstream's bytes.
    let payload = entry["canonical"].as_str().unwrap().as_bytes();
    assert_eq!(keypair.sign(payload).to_hex(), UPSTREAM_SIGNATURE);
}

#[test]
fn tampering_with_any_byte_breaks_verification() {
    let doc = vectors();
    let pk = Keypair::from_seed_hex(doc["seed_hex"].as_str().unwrap())
        .unwrap()
        .public_key();

    for entry in doc["payloads"].as_array().unwrap() {
        let id = entry["id"].as_str().unwrap();
        let signature = entry["signature_hex"].as_str().unwrap();
        let canonical = entry["canonical"].as_str().unwrap();
        let sig = nau_core::Signature64::from_hex(signature).unwrap();

        // Flip the last byte of the payload.
        let mut tampered = canonical.as_bytes().to_vec();
        let last = tampered.len() - 1;
        tampered[last] ^= 0x01;
        assert!(
            pk.verify(&tampered, sig.as_bytes()).is_err(),
            "[{id}] a tampered payload must not verify"
        );

        // Truncate the payload.
        assert!(
            pk.verify(&canonical.as_bytes()[..canonical.len() - 1], sig.as_bytes())
                .is_err(),
            "[{id}] a truncated payload must not verify"
        );
    }
}

#[test]
fn the_fixture_pins_every_documented_rejection() {
    let doc = vectors();
    let rejections = doc["rejections"].as_array().expect("rejections array");
    assert!(!rejections.is_empty(), "fixture must pin rejection cases");

    for entry in rejections {
        let id = entry["id"].as_str().unwrap();
        let kind = entry["error"].as_str().unwrap();
        let parsed: Value = serde_json::from_str(entry["input_json"].as_str().unwrap())
            .unwrap_or_else(|e| panic!("[{id}] input_json must parse: {e}"));

        let err = canonical_object(&parsed)
            .err()
            .unwrap_or_else(|| panic!("[{id}] must be rejected but canonicalized successfully"));
        assert!(
            expected_error(kind)(&err),
            "[{id}] expected {kind}, got {err:?}"
        );
    }
}

#[test]
fn floats_are_rejected_wherever_they_hide() {
    // Top level, nested, and inside an array: the rule is structural.
    for input in [
        r#"{"a":1.0}"#,
        r#"{"a":{"b":2.5}}"#,
        r#"{"a":[1,2.5]}"#,
        r#"{"a":1e2}"#,
        r#"{"a":-0.0}"#,
    ] {
        let v: Value = serde_json::from_str(input).unwrap();
        let err = canonical_object(&v).unwrap_err();
        assert!(
            matches!(err, CanonicalError::NonIntegerNumber(_)),
            "input {input} must be refused, got {err:?}"
        );
    }
}

#[test]
fn identifiers_and_signatures_reject_malformed_encodings() {
    assert!(PublicKey::from_hex("").is_err());
    assert!(PublicKey::from_hex("00").is_err());
    assert!(PublicKey::from_hex(&"zz".repeat(32)).is_err());
    assert!(nau_core::Signature64::from_hex("").is_err());
    assert!(nau_core::Signature64::from_hex(&"00".repeat(63)).is_err());
    assert!(nau_core::Signature64::from_hex(&"zz".repeat(64)).is_err());
    // A signature of the right length decodes; it simply will not verify.
    assert!(nau_core::Signature64::from_hex(&"00".repeat(64)).is_ok());
}
